name: Update Global Version

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-version]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout version manager repo
        uses: actions/checkout@v3

      - name: Get backend version from pom.xml
        id: backend
        run: |
          url="https://raw.githubusercontent.com/sdi25-source/SDI-Backend/main/pom.xml"
          version=$(curl -s $url | grep -oPm1 "(?<=<version>)[^<]+")
          echo "backend_version=$version" >> $GITHUB_OUTPUT

      - name: Get frontend version from package.json
        id: frontend
        run: |
          url="https://raw.githubusercontent.com/sdi25-source/SDI-Frontend/main/package.json"
          version=$(curl -s $url | jq -r '.version')
          echo "frontend_version=$version" >> $GITHUB_OUTPUT

      - name: Read old global version
        id: old
        run: |
          if [ -f version-global.txt ]; then
            echo "old_global_version=$(cat version-global.txt)" >> $GITHUB_OUTPUT
          else
            echo "old_global_version=" >> $GITHUB_OUTPUT
          fi

      - name: Compute and write new global version
        id: compute
        run: |
          frontend=${{ steps.frontend.outputs.frontend_version }}
          backend=${{ steps.backend.outputs.backend_version }}
          version="${frontend}-${backend}"
          echo "$version" > version-global.txt
          echo "artifact_name=f${frontend}-b${backend}" >> $GITHUB_OUTPUT
          echo "new_global_version=$version" >> $GITHUB_OUTPUT

      - name: Commit new version
        if: steps.old.outputs.old_global_version != steps.compute.outputs.new_global_version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add version-global.txt
          git commit -m "Update global version to ${{ steps.compute.outputs.new_global_version }}"
          git push

      - name: Tag new version
        if: steps.old.outputs.old_global_version != steps.compute.outputs.new_global_version
        run: |
          git tag "global-v${{ steps.compute.outputs.new_global_version }}"
          git push origin --tags

      - name: Create version-info artifact
        run: |
          echo "Frontend Version: ${{ steps.frontend.outputs.frontend_version }}" > version-info.txt
          echo "Backend Version:  ${{ steps.backend.outputs.backend_version }}" >> version-info.txt
          echo "Global Version:   ${{ steps.compute.outputs.new_global_version }}" >> version-info.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.compute.outputs.artifact_name }}
          path: version-info.txt
